# Generated by Django 3.2.7 on 2022-05-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nmap',
            name='port_range',
        ),
    ]
