# Generated by Django 3.2.7 on 2022-05-18 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_Subdomain',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('target', models.CharField(default='127.0.0.1', max_length=255)),
            ],
            bases=('api.basemodel',),
        ),
        migrations.RemoveField(
            model_name='nmap',
            name='port_range',
        ),
        migrations.RemoveField(
            model_name='nmap',
            name='response',
        ),
        migrations.AddField(
            model_name='basemodel',
            name='response',
            field=models.JSONField(default=dict, editable=False, null=True),
        ),
    ]
