# Generated by Django 3.2.7 on 2022-05-10 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_nmap_port_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebCrawler',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
            ],
            bases=('api.basemodel',),
        ),
        migrations.RemoveField(
            model_name='nmap',
            name='response',
        ),
        migrations.RemoveField(
            model_name='nmap',
            name='target',
        ),
        migrations.AddField(
            model_name='basemodel',
            name='response',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='target',
            field=models.CharField(default='127.0.0.1', max_length=255),
        ),
    ]
