# Generated by Django 3.2.7 on 2022-05-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220510_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='response',
            field=models.JSONField(default=dict, editable=False, null=True),
        ),
    ]
